name: .NET Core release

on:
  push:
    tags: 
      - 'v*'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore HJM.Chip8/HJM.Chip8.sln
    - name: Test
      run: dotnet test HJM.Chip8/HJM.Chip8.sln --verbosity normal
    - name: Build win-x64
      run: |
        dotnet publish HJM.Chip8/HJM.Chip8.MonoGameUI/HJM.Chip8.MonoGameUI.csproj -c Release -r win-x64 /p:PublishReadyToRun=false /p:TieredCompilation=false --self-contained
        cd HJM.Chip8/HJM.Chip8.MonoGameUI/bin/Release/netcoreapp3.1/win-x64/publish
        zip -r Chip8-win-x64.zip *
        mv Chip8-win-x64.zip ../../../../../../../Chip8-win-x64.zip
    - name: Build osx-x64
      run: |
        dotnet publish HJM.Chip8/HJM.Chip8.MonoGameUI/HJM.Chip8.MonoGameUI.csproj -c Release -r osx-x64 /p:PublishReadyToRun=false /p:TieredCompilation=false --self-contained
        cd HJM.Chip8/HJM.Chip8.MonoGameUI/bin/Release/netcoreapp3.1/osx-x64/publish
        zip -r Chip8-osx-x64.zip *
        mv Chip8-osx-x64.zip ../../../../../../../Chip8-osx-x64.zip
    - name: Build linux-x64
      run: |
        dotnet publish HJM.Chip8/HJM.Chip8.MonoGameUI/HJM.Chip8.MonoGameUI.csproj -c Release -r linux-x64 /p:PublishReadyToRun=false /p:TieredCompilation=false --self-contained
        cd HJM.Chip8/HJM.Chip8.MonoGameUI/bin/Release/netcoreapp3.1/linux-x64/publish
        zip -r Chip8-linux-x64.zip *
        mv Chip8-linux-x64.zip ../../../../../../../Chip8-linux-x64.zip
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ steps.get_version.outputs.VERSION }}"
        prerelease: false
        files: |
            license.txt
            readme.md
            Chip8-win-x64.zip
            Chip8-osx-x64.zip
            Chip8-linux-x64.zip
