name: .NET Core pre release

on:
  push:
    branches: [ master ]

jobs:
  pre-release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore HJM.Chip8/HJM.Chip8.sln
    - name: Build
      run: dotnet build HJM.Chip8/HJM.Chip8.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test HJM.Chip8/HJM.Chip8.sln --no-restore --verbosity normal
    - name: Change to build directory to zip
      run: cd HJM.Chip8/HJM.Chip8.MonoGameUI/bin/Release/netcoreapp3.1/
    - name: Zip
      run: zip -r Chip8.zip *
    - name: ls
      run: ls
    - name: Change back to root
      run: cd ../../../../../
    - name: ls
      run: ls
    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "prereleased"
        prerelease: true
        title: "Development Build"
        files: |
            license.txt
            HJM.Chip8/HJM.Chip8.MonoGameUI/bin/Release/netcoreapp3.1/Chip8.zip